# Generated by Django 3.1.1 on 2020-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
                ('body', models.CharField(max_length=1000)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
